---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: echo-demo-deployment
  labels:
    app: echo-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-demo
  template:
    metadata:
      labels:
        app: echo-demo
    spec:
      containers:
      - name: echo-demo
        image: jmalloc/echo-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "1.0.0"
