---
kind: Service
apiVersion: v1
metadata:
  name: echo-demo-service # Service name
  labels:
    app: echo-demo
spec:
  type: LoadBalancer
  selector:
    app: echo-demo # Label selector. The Service targets Pods that use this label
  ports:
    - port: 80 # Port used to access the Service from within the cluster.
      targetPort: 8080 # Port opened by targeted Pods